version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: "composer"
    directory: "/python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
  # C#
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆